version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bulletify_creator
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: bulletify_creator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
